apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-dashboard
  title: Analytics Dashboard
  description: A website for analytics dashboards with metrics and information about StaffingHQ
  annotations:
    github.com/project-slug: Staffing-HQ/analytics-dashboard
    backstage.io/techdocs-ref: dir:.
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
  tags:
    - nextjs
    - react
    - ssr
spec:
  type: website
  lifecycle: experimental
  owner: group:default/data-analytics
