apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-dashboard
  title: Analytics Dashboard
  description: A website for analytics dashboards with metrics and information about StaffingHQ
  annotations:
    github.com/project-slug: Staffing-HQ/analytics-dashboard
    backstage.io/techdocs-ref: dir:.
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
    sonarqube.org/project-key: Staffing-HQ_analytics-dashboard
  links:
    - url: https://www.youtube.com/watch?v=dQw4w9WgXcQ
      title: Website
      icon: dashboard
  tags:
    - nextjs
    - react
    - ssr
    - admin-dashboard
spec:
  type: website
  lifecycle: experimental
  owner: group:default/data-analytics
  system: analytics-system
  dependsOn: ['api:users-srv-api', 'api:internships-srv-api', 'api:employees-srv-api', 'api:auth-srv-api']
